services:
  router:
    build: router
    restart: always
    init: yes
    ports:
    - 80:80
    - 443:443
    links:
    - webdav:webdav
  syncthing:
    image: linuxserver/syncthing:latest
    restart: always
    ports:
      - 8384:8384
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - syncthing_config:/config
      - syncthing_data:/data1
    healthcheck:
      test: 'nc -z "$${HOSTNAME}" 8384 || exit 1'
      interval: 60s
      timeout: 10s
  webdav:
    build: webdav
    restart: always
    init: true
    environment:
      WEBDAV_PASSWORD_DORIDIAN: ${WEBDAV_PASSWORD_DORIDIAN}
    volumes:
     - webdav_config:/config
     - webdav_data:/data
  autoheal:
    restart: always
    userns-mode: host
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  syncthing_config: {}
  syncthing_data: {}
  webdav_config: {}
  webdav_data: {}
